apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin
  namespace: skillometer
  labels:
    app: web-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-admin
  template:
    metadata:
      labels:
        app: web-admin
    spec:
      containers:
        - name: web-admin
          image: ilyamachetto/skillometer-web-admin:0.6.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: web-admin
  namespace: skillometer
spec:
  selector:
    app: web-admin
  ports:
    - protocol: TCP
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 8080
